- name: Deploy and run app
  hosts: all
  gather_facts: no
  remote_user: appuser

  tasks:

    - name: Add docker key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repo
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker-ce docker-compose
      become: yes
      apt:
        name: "{{item}}"
        update_cache: yes
      with_items:
        - docker-ce
        - docker-compose

    - name: Get docker-compose version
      shell: docker-compose -v | awk '{print $3}'
      register: docker_compose_version

    - name: Download docker-compose
      become: yes
      get_url:
        url: https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
        force: yes
      when: docker_compose_version != "1.19.0,"

    - name: Deploy reddit-microservices
      synchronize:
        src: ../reddit-microservices
        dest: ~/

    - name: Set .env file
      command: mv .env.example .env

    - name: Start app
      shell: cd ~/reddit-microservices && sudo docker-compose down && sudo docker-compose up -d

