#APP_EXT_PORT=9292
#APP_UI_VERSION=1.0
#APP_POST_VERSION=1.0
#APP_COMMENT_VERSION=1.0
#MONGO_VERSION=3.2


version: '3.3'
services:
  post_db:
    container_name: c_post_db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    container_name: c_ui
    build: ./ui
    image: 35.187.176.178:4567/homework/example2/reddit-ui/${BRANCH}
    ports:
      - ${APP_EXT_PORT}:9292/tcp
    networks:
      - reddit
  post:
    container_name: c_post
    build: ./post-py
    image: 35.187.176.178:4567/homework/example2/post-py/${BRANCH}
    networks:
      reddit:
        aliases:
          - post
  comment:
    container_name: c_comment
    build: ./comment
    image: 35.187.176.178:4567/homework/example2/comment/${BRANCH}
    networks:
      reddit:
        aliases:
          - comment

volumes:
  post_db:

networks:
  reddit:
