image: ruby:2.4.2

stages:
  - build
  - create_vm
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
#  - cd reddit
#  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

create_vm_job:
  stage: create_vm
  script:
    - apt update && apt install -y python-pip python-dev
    - pip install virtualenv pycrypto
    - virtualenv -p python2.7 env
    - source env/bin/activate
    - pip install ansible apache-libcloud
    - echo "${GCP_CREDS_JSON}" | base64 -d > Docker-72e3439b3339.json
    - ansible-playbook hw_20/create_instance.yaml --extra-vars="credentials_file=../Docker-72e3439b3339.json state=active"
  environment:
    name: vm/$CI_COMMIT_REF_NAME
    on_stop: stop_vm
  only:
    - branches
  except:
    - master

stop_vm:
  stage: create_vm
  when: manual
  script:
    - apt update && apt install -y python-pip python-dev
    - pip install virtualenv pycrypto
    - virtualenv -p python2.7 env
    - source env/bin/activate
    - pip install ansible apache-libcloud
    - echo "${GCP_CREDS_JSON}" | base64 -d > Docker-72e3439b3339.json
    - ansible-playbook hw_20/create_instance.yaml --extra-vars="credentials_file=../Docker-72e3439b3339.json state=deleted"
  environment:
    name: vm/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
