kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: CDk0tVQJKUxoiV4JMRE+kaZxU3EAuF7t7u5KiEo967c=
      - identity: {}
