version: '3'
services:
  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - reddit

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - reddit

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    networks:
      - reddit

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - reddit

networks:
  reddit:
