version: '3.3'
services:

  post_db:
    container_name: c_post_db
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db

  ui:
    container_name: c_ui
    image: ${USERNAME}/ui:${APP_UI_VERSION}
    ports:
      - ${APP_EXT_PORT}:9292/tcp
    networks:
      - reddit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  post:
    container_name: c_post
    image: ${USERNAME}/post:${APP_POST_VERSION}
    networks:
      reddit:
        aliases:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    container_name: c_comment
    image: ${USERNAME}/comment:${APP_COMMENT_VERSION}
    networks:
      reddit:
        aliases:
          - comment

volumes:
  post_db:

networks:
  reddit:
